package cmd

import (
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/ui-engine/core/config"
)

// Gen генерирует Go-типы из контрактов net.yaml и state.yaml в папку generated/.
//
// Источник типов — контракты config (Field/Variable), повторяющие JSON-Schema
// ($defs.field / $defs.variable). Маркер "Code generated" гарантирует идемпотентность:
// повторный запуск перезаписывает файлы тем же детерминированным содержимым.
func Gen(root string) error {
	abs, err := filepath.Abs(root)
	if err != nil {
		return err
	}
	loader := config.NewLoader(abs)
	app, err := loader.LoadApp()
	if err != nil {
		return fmt.Errorf("app.yaml: %w", err)
	}

	// net.yaml (опционально) и state.yaml (опционально)
	netCfg, err := loader.LoadNet(optionalPath(app.NetPath, "net.yaml"))
	if err != nil {
		return fmt.Errorf("net.yaml: %w", err)
	}
	stateCfg, err := loader.LoadState(optionalPath(app.StatePath, "state.yaml"))
	if err != nil {
		return fmt.Errorf("state.yaml: %w", err)
	}

	genDir := filepath.Join(abs, "generated")
	if err := os.MkdirAll(genDir, 0o755); err != nil {
		return err
	}

	g := &generator{used: map[string]int{}}

	var needSend, hasNet bool
	var netModels, netSend, stateModels strings.Builder

	if fileExists(filepath.Join(abs, optionalPath(app.NetPath, "net.yaml"))) {
		netModels.WriteString(g.header())
		hasNet = true
		netSend.WriteString(g.header())
		netSend.WriteString("import \"github.com/ui-engine/core/net\"\n\n")
		needSend = true
		genNetModels(g, &netModels, &netSend, netCfg)
	}

	if fileExists(filepath.Join(abs, optionalPath(app.StatePath, "state.yaml"))) {
		stateModels.WriteString(g.header())
		genStateModels(g, &stateModels, stateCfg)
	}

	if err := writeFormatted(filepath.Join(genDir, "net_models.go"), netModels.String()); err != nil {
		return err
	}
	if err := writeFormatted(filepath.Join(genDir, "net_send.go"), netSend.String()); err != nil {
		return err
	}
	if err := writeFormatted(filepath.Join(genDir, "state_models.go"), stateModels.String()); err != nil {
		return err
	}

	fmt.Printf("✓ generated/ создано (%s)\n", genDir)
	if hasNet {
		fmt.Println("  • net_models.go (типы payload/request из net.yaml)")
		if needSend {
			fmt.Println("  • net_send.go (типизированные функции-отправки)")
		}
	}
	if stateModels.Len() > 0 {
		fmt.Println("  • state_models.go (типы состояния из state.yaml)")
	}
	return nil
}

func optionalPath(p, def string) string {
	if p == "" {
		return def
	}
	return p
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

// writeIfChanged форматирует код (go/format) и перезаписывает файл,
// только если содержимое изменилось.
func writeFormatted(path, raw string) error {
	src, err := format.Source([]byte(raw))
	if err != nil {
		// Пишем как есть: это уже валидный Go, но без выравнивания.
		src = []byte(raw)
	}
	if old, err := os.ReadFile(path); err == nil && string(old) == string(src) {
		return nil
	}
	return os.WriteFile(path, src, 0o644)
}

// generator раздаёт уникальные имена типов.
type generator struct {
	used map[string]int
}

func (g *generator) unique(name string) string {
	if g.used[name] == 0 {
		g.used[name] = 1
		return name
	}
	g.used[name]++
	return fmt.Sprintf("%s%d", name, g.used[name])
}

func (g *generator) header() string {
	return "// Code generated by ui-engine gen. DO NOT EDIT.\n" +
		"// Источник типов: контракты net.yaml и state.yaml (см. JSON-Schema).\n\n" +
		"package generated\n\n"
}

// genNetModels генерирует структуры из server events и client events.
func genNetModels(g *generator, models, send *strings.Builder, netCfg *config.Net) {
	// server events -> типы payload
	for _, ev := range sortedKeys(netCfg.Events.Server) {
		se := netCfg.Events.Server[ev]
		if len(se.Payload) == 0 {
			continue
		}
		typeName := g.unique(goIdent(ev))
		g.genStruct(models, typeName, ev+" payload", fieldsFrom(se.Payload))
	}
	// client events -> типы request + функции-отправки
	for _, ev := range sortedKeys(netCfg.Events.Client) {
		ce := netCfg.Events.Client[ev]
		if len(ce.Request) == 0 {
			continue
		}
		reqName := g.unique(goIdent(ev) + "Request")
		g.genStruct(models, reqName, ev+" request", fieldsFrom(ce.Request))
		g.genSend(send, ev, reqName, ce.Request)
	}
}

// fieldsFrom строит поля структуры из схемы Field-ов, сортируя по имени.
func fieldsFrom(fields map[string]config.Field) []map[string]any {
	keys := sortedKeys(fields)
	out := make([]map[string]any, 0, len(keys))
	for _, k := range keys {
		f := fields[k]
		out = append(out, map[string]any{
			"key":   k,
			"goType": goType(f.Type),
			"goIdent": goIdent(k),
			"required": f.Required,
			"secret":   f.Secret,
			"comment":  f.Type,
		})
	}
	return out
}

// genStruct выводит "type <Name> struct { ... }".
func (g *generator) genStruct(b *strings.Builder, name, doc string, fields []map[string]any) {
	if doc != "" {
		fmt.Fprintf(b, "// %s — %s.\n", name, doc)
	} else {
		fmt.Fprintf(b, "// %s.\n", name)
	}
	fmt.Fprintf(b, "type %s struct {\n", name)
	for _, f := range fields {
		fmt.Fprintf(b, "\t%s %s", f["goIdent"].(string), f["goType"].(string))
		if f["secret"].(bool) {
			fmt.Fprintf(b, " `json:\"-\"`")
		} else {
			fmt.Fprintf(b, " `json:\"%s\"`", f["key"].(string))
		}
		if !f["required"].(bool) {
			b.WriteString(" // optional")
		}
		b.WriteString("\n")
	}
	b.WriteString("}\n\n")
}

// genSend генерирует типизированные функции-отправки.
func (g *generator) genSend(b *strings.Builder, ev, reqName string, fields map[string]config.Field) {
	fmt.Fprintf(b, "// Send%sPayload собирает payload события %q.\n", goIdent(ev), ev)
	fmt.Fprintf(b, "func Send%sPayload(req %s) map[string]any {\n", goIdent(ev), reqName)
	fmt.Fprintf(b, "\treturn map[string]any{\n")
	for _, k := range sortedKeys(fields) {
		f := fields[k]
		if f.Secret {
			continue
		}
		fmt.Fprintf(b, "\t\t%q: req.%s,\n", k, goIdent(k))
	}
	fmt.Fprintf(b, "\t}\n")
	fmt.Fprintf(b, "}\n\n")
	fmt.Fprintf(b, "// Send%s отправляет событие %q с типизированным запросом.\n", goIdent(ev), ev)
	fmt.Fprintf(b, "func Send%s(c *net.Client, req %s) {\n", goIdent(ev), reqName)
	fmt.Fprintf(b, "\tc.Send(%q, Send%sPayload(req))\n", ev, goIdent(ev))
	fmt.Fprintf(b, "}\n\n")
}

// genStateModels генерирует типы состояния из state.yaml.
func genStateModels(g *generator, b *strings.Builder, st *config.State) {
	for _, name := range sortedKeys(st.Vars) {
		v := st.Vars[name]
		switch v.Type {
		case "object":
			if len(v.Fields) == 0 {
				fmt.Fprintf(b, "// %s — произвольный объект состояния (без схемы полей).\n", goIdent(name))
				fmt.Fprintf(b, "type %s map[string]any\n\n", goIdent(name))
				continue
			}
			g.genStruct(b, g.unique(goIdent(name)), "состояние "+name, stateFields(v.Fields))
		default:
			fmt.Fprintf(b, "// %s — %s.\n", goIdent(name), v.Type)
			fmt.Fprintf(b, "type %s %s\n\n", g.unique(goIdent(name)), goType(v.Type))
		}
	}
}

func stateFields(fields map[string]config.Variable) []map[string]any {
	keys := sortedKeys(fields)
	out := make([]map[string]any, 0, len(keys))
	for _, k := range keys {
		f := fields[k]
		out = append(out, map[string]any{
			"key":     k,
			"goType":  goType(f.Type),
			"goIdent": goIdent(k),
			"required": f.Required,
			"secret":   f.Secret,
			"comment":  f.Type,
		})
	}
	return out
}

// goType маппит тип контракта Field/Variable в Go-тип.
func goType(t string) string {
	switch t {
	case "int":
		return "int"
	case "float":
		return "float64"
	case "bool":
		return "bool"
	case "object":
		return "map[string]any"
	case "list":
		return "[]any"
	default:
		return "string"
	}
}

// initialisms — распространённые акронимы, которые сохраняются в верхнем регистре.
var initialisms = map[string]string{
	"id": "ID",
	"url": "URL",
	"uri": "URI",
	"api": "API",
	"http": "HTTP",
	"tcp": "TCP",
	"ws": "WS",
}

// goIdent преобразует ключ (точки/слэши/подчёркивания) в Go-идентификатор CamelCase.
func goIdent(s string) string {
	segs := strings.FieldsFunc(s, func(r rune) bool {
		return r == '.' || r == '/' || r == '-' || r == '_' || r == ' '
	})
	var b strings.Builder
	for _, seg := range segs {
		if seg == "" {
			continue
		}
		if up, ok := initialisms[strings.ToLower(seg)]; ok {
			b.WriteString(up)
			continue
		}
		rs := []rune(seg)
		i := 0
		if rs[0] >= '0' && rs[0] <= '9' {
			b.WriteString("V")
			for i < len(rs) && rs[i] >= '0' && rs[i] <= '9' {
				i++
			}
		}
		if i < len(rs) {
			rs[i] = unicode.ToUpper(rs[i])
		}
		b.WriteString(string(rs))
	}
	if b.Len() == 0 {
		return "Value"
	}
	return b.String()
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}